spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/studs
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
jwt.secret=${SECRET:i-am-optimus-prime-and-i-send-this-message-to-any-surviving-autobots-taking-refuge-among-the-stars}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.eclipse.persistence.platform.database.PostgreSQLPlatform
spring.jpa.properties.eclipselink.ddl-generation=create-or-extend-tables
spring.jpa.properties.eclipselink.logging.level.sql=FINE
spring.jpa.properties.eclipselink.logging.parameters=true
spring.jpa.properties.eclipselink.weaving=false
spring.jpa.properties.eclipselink.cache.shared.daefault=false
spring.jpa.properties.eclipselink.logging.logger=DefaultLogger
